resolver: nightly-2018-06-21
packages:
- './src/h3-core'
- './src/h3-concur-react'
- './src/h3-colour'
- './src/h3-examples'  
- './src/h3-geo'
- './src/h3-svg'

flags: {}

extra-package-dbs: []

extra-deps:

- ghcjs-base-stub-0.2.0.0

# readshp on hackage requires base <4.9
- git: git@github.com:j-mueller/readshp.git
  commit: 6a09e93e584db96b60b62d560a503dad7f512e29

# concur not currently on hackage
- git: git@github.com:j-mueller/concur.git
  commit: 71ea66eb338425965edfdd65eb10c5a1fb833149
  subdirs:
  - concur-core
  - concur-react